### ISSUE TITLE
Add Mounting Holes

### ISSUE THREAD

**Issue by shannietron** [sayanee/belle#10]

**Comment by sayanee** [comment]
- Front view of the 3 AA battery holder
   ![image](https://cloud.githubusercontent.com/assets/413879/25686765/65be0aec-30a3-11e7-950f-f6178d7c6de5.png)
- Back of the 3 AA battery holder
    ![img_2166](https://cloud.githubusercontent.com/assets/413879/25686670/a73de060-30a2-11e7-991d-7f3f159d2bb1.JPG)
- M3 screw head
    ![image](https://cloud.githubusercontent.com/assets/413879/25686690/d3d5f2d4-30a2-11e7-9594-6f5986f80858.png)
- 2 M3 screws separated by `3cm`

**Comment by sayanee** [comment]
closed with https://github.com/sayanee/belle/commit/2d6acd98b846e6787d95b16f563462086defe06c
