### ISSUE TITLE
Silkscreen Layers During Gerber Generation

### ISSUE THREAD

**Issue by shannietron** [sayanee/belle#12]
Ensure the correct layers are picked during gerber generation. Right now, the top silkscreen layer looks like this. Things like V1.0 didn't show up. 

<img width="929" alt="gerber_slikscreen" src="https://cloud.githubusercontent.com/assets/905539/24130033/a8dfb532-0dbc-11e7-8125-bbaf96d593f7.png">

Another option is to move text you want in the silkscreen to the silkscreen layer.

**Comment by sayanee** [comment]
closed with https://github.com/sayanee/belle/commit/2d6acd98b846e6787d95b16f563462086defe06c
