### ISSUE TITLE
Unable to flash with ESP12F modules

### ISSUE THREAD

**Issue by sayanee** [sayanee/belle#14]
## Steps to reproduce

1. Wire up an `ESP12F module` (taking reference from [Huzzah schematic](https://cdn-learn.adafruit.com/assets/assets/000/024/745/original/adafruit_products_schem.png?1429900999))
    - `GND` to `0V`
    - `GPIO15` to `0V`  via a `10kΩ` resistor
    - `GPIO2` to `3V3`  via a `10kΩ` resistor
    - `GPIO0` to `0V`  via a `10kΩ` resistor
    - `GPIORX` to `TX` on serial
    - `GPIOTX` to `RX` on serial
    - `VCC` to `3V3`
    - `CHPD` to `3V3`
    - `RST` the chip by connecting rest to `0V` briefly before flashing
    ![img_1951](https://cloud.githubusercontent.com/assets/413879/25300085/46a3d4ba-273a-11e7-892b-b91b015db391.JPG)
1. Connect to the MacBook via the [serial console cable](https://www.adafruit.com/product/954)
1. Open up Arduino IDE to flash a blinky program

    ```c
    void setup() {
      pinMode(LED_BUILTIN, OUTPUT);
    }

    void loop() {
      digitalWrite(LED_BUILTIN, LOW);                   
      delay(1000);                   
      digitalWrite(LED_BUILTIN, HIGH);
      delay(2000);
    }
    ```
    
    ![screenshot 2017-04-22 08 57 23](https://cloud.githubusercontent.com/assets/413879/25300060/d31fc26a-2739-11e7-88bf-966780e88e01.png)

## Actual result

1. Turn on the serial monitor
1. Reset ESP12
1. Upload the program
1. Arduino is having an error when flashing

![screenshot 2017-04-22 09 02 33](https://cloud.githubusercontent.com/assets/413879/25300098/714f8bf0-273a-11e7-8eae-2107f804e4db.png)

## Expected result

1.  Turn on the serial monitor in Arduino IDE
1. Reset ESP12
1. Serial monitor should show `waiting for download`
1. Arduino should be successful in flashing the blinky progam

**Comment by sayanee** [comment]
@shannietron any idea? 🤔

**Comment by notthetup** [comment]
Instructions from Adafruit for flashing firmware.

Maybe GPIO0 can't be tied to ground all the time. https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/using-arduino-ide

> Hold down the GPIO0 button, the red LED will be lit
> While holding down GPIO0, click the RESET button
> Release RESET, then release GPIO0
> When you release the RESET button, the red LED will be lit dimly, this means its ready to bootload

**Comment by sayanee** [comment]
> turn on serial monitor then reset, can you see something like 'waiting for download'?

nope, nothing

> that's not right. even if not enter program made there need be something. maybe check serial connection?

**Comment by sayanee** [comment]
Wired it like Huzzah and the serial monitor gives the following in infinite loops:

```sh
Fatal exception (0): epc1=0x40100003, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```

ESP drawing `30mA`

PS: With some wrong wiring, the above exception shows. Else the serial monitor is empty.

**Comment by sayanee** [comment]
# Solution

1. Use a proper [FTDI chip](https://world.taobao.com/item/13702527783.htm?fromSite=main&ut_sk=1.UpdigsCXw0cDAECxW5pO7mwr_21380790_1493626825951.Copy.1&sourceType=item&price=25&suid=D6574792-6BAA-4E74-A821-5A4BCA83B2A8&cpp=1&shareurl=true&spm=a313p.22.2r6.36666827659&short_name=h.gE7eOv&cv=2jSFZGYevmU&sm=d06db6&app=chrome)
1. Be careful of shorting ESP12 module pins while soldering

# Minimum wiring

- ESP8266
    - `VCC` pin to `3.3V`
    - `EN` pin to `3.3V`
    - `GND` pin to `GND`
    - `GPIO15`	to `GND` with a resistor
    - `GPIO2` to `3.3V` with a resistor	
- Battery
    - `5V` to `5V` rail
    - `GND` to `GND` rail

## Modes

> To enable ESP8266 firmware flashing GPIO0 pin must be pulled low before the device is reset. Conversely, for a normal boot, GPIO0 must be pulled high or floating. [[Ref](https://nodemcu.readthedocs.io/en/master/en/flash/#putting-device-into-flash-mode)]

### Flashing mode

- FTDI chip
    - `GND` to `GND` 
    - `TX` pin to `RX` of ESP8266
    - `RX` pin to `TX` of ESP8266
    - `VCC` pin to `5V` rail of the breadboard
- ESP8266, ESP-12 module
    - `RX` pin to `TX` of FTDI chip
    - `TX` pin to `RX` of FTDI chip
- **Flashing mode**: Minimum wiring + extra wiring - `boot mode:(1,x)`
    - Plug in `GPIO0` of ESP8266 to `GND`
    - Plug out and plug in `VCC` of ESP8266

    ```sh
     ets Jan  8 2013,rst cause:2, boot mode:(1,1)
    ```
    - Flash the firmware

    ```c
    void setup() { 
      pinMode(2, OUTPUT); // GPIO02 on ESP-12 module is linked to on-board LED
      Serial.begin(9600);
      Serial.println("setup"); 
    } 

    void loop() { 
      digitalWrite(2, HIGH);
      Serial.println("HIGH"); 
      delay(1000);
      digitalWrite(2, LOW);
      delay(1000);
    }
    ```
    - See the on-board blue LED blink every second

### Normal mode

- **Normal mode**: Minimum wiring + extra wiring - `boot mode:(3,x)`
    - Pull out `VCC` of ESP8266 and put back in / plug in the battery
    - View the serial monitor in Arduino IDE with baud rate `74880`
    ```sh
     ets Jan  8 2013,rst cause:2, boot mode:(3,6)
    ```
    - Change baud rate according to the flashed firmware to see any `Serial.Println()`

**Comment by sayanee** [comment]
## Normal mode

> serial monitor output

![screenshot 2017-05-01 17 00 48](https://cloud.githubusercontent.com/assets/413879/25600040/a14ef422-2f13-11e7-923e-a0ae25f5bb54.png)

## Boot mode

> serial monitor output

![screenshot 2017-05-01 17 00 55](https://cloud.githubusercontent.com/assets/413879/25600049/ad2f7032-2f13-11e7-93a4-e994f6021265.png)

**Comment by notthetup** [comment]
https://github.com/esp8266/esp8266-wiki/wiki/Boot-Process#esp-boot-modes

**Comment by sayanee** [comment]
| GPIO15 | GPIO0 | GPIO2 | Mode | Description | Binary | Decimal
| ------ | ------ | ------ | ------ | ------ | ------ | ------
| L | L | H | UART | Download code from UART | 001 | 1
| L | H | H | Flash | Boot from SPI Flash | 011 | 3
| H | x | x | SDIO | Boot from SD-card | 100, 101, 110, 111 | 4, 5, 6, 7

**Comment by sayanee** [comment]
See [edited solution](https://github.com/sayanee/belle/issues/14#issuecomment-298308491)
