### ISSUE TITLE
capacitor

### ISSUE THREAD

**Issue by sayanee** [sayanee/belle#3]
values

> your decoup caps C2 C3 C4 -- i know these are the datasheets' basic recommendations, but it doesn't hurt to make them slightly larger, especially this is a "one-off" prototype you're building. It'd be nice if C4 is `47-100uF`, and C2 is `47uF`. It's just a feeling 'cos ppl have issues during the early prototypes around the esp8266.

add more capacitors:

1. AP2112 pin `OUT` and pin `IN` with additional `1nF` 
1. ESP pin `VCC` with additional `1nF`

**Comment by shannietron** [comment]
Since you have a fair bit of space in the PCBs, you can add empty pads for capacitors in parallel to the other decoupling caps. So that in the future if you encounter issues and want to add a decoupling cap, it is easy to do.
