### ISSUE TITLE
flashing connector

### ISSUE THREAD

**Issue by sayanee** [sayanee/belle#5]
> Is P3 configured to any of your usual USB-Serial adapters pinout?

standard from [dfrobot](https://www.dfrobot.com/)

**Comment by notthetup** [comment]
For example : https://www.dfrobot.com/product-581.html

There seem to be a couple of "standards".

![_dsc0140-900x600](https://cloud.githubusercontent.com/assets/553140/24102769/f1f5e318-0db7-11e7-8bb3-8dd21182cf10.jpg)

![screenshot 2017-03-20 21 53 52](https://cloud.githubusercontent.com/assets/553140/24102707/c5089bfc-0db7-11e7-8907-e5d43af1094d.jpg)

**Comment by sayanee** [comment]
sticking to the original pin layout

**Comment by sayanee** [comment]
Decided to use the standard connector (related to #14) using FTDI chip
