### ISSUE TITLE
fix vias and trace width dimensions

### ISSUE THREAD

**Issue by sayanee** [sayanee/belle#7]
> a small problem in the PCB. Via's diameter is too small. Typical board house will need 0.15mm on both sides of the hole, so minimum you need via size = hole size + 0.3mm

**Comment by notthetup** [comment]
Check with your fab house, what trace sizes and via sizes they can do.

This is what https://github.com/notthetup/draw uses.

![screenshot 2017-03-20 22 16 19](https://cloud.githubusercontent.com/assets/553140/24103687/0044c648-0dbb-11e7-8ac7-0ffed5f2f402.jpg)

**Comment by sayanee** [comment]
closed with https://github.com/sayanee/belle/commit/2d6acd98b846e6787d95b16f563462086defe06c
